drop table cities cascade Constraints;

CREATE TABLE  "CITIES" 
   (	"CI" VARCHAR2(30), 
	"CITY_NAME" VARCHAR2(30)
   )
/


INSERT INTO CITIES (CI, CITY_NAME) VALUES ('BA', 'Bath');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('BI', 'Birmingham');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('BR', 'Bradford');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('BH', 'Brighton & Hove');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('BS', 'Bristol');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CA', 'Cambridge');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CN', 'Canterbury');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CR', 'Carlisle');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CH', 'Chelmsford');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CT', 'Chester');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CC', 'Chichester');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CO', 'Colchester');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CV', 'Coventry');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('DE', 'Derby');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('DC', 'Doncaster');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('DU', 'Durham');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('EL', 'Ely');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('EX', 'Exeter');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('GL', 'Gloucester');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('HF', 'Hereford');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('KH', 'Kingston-upon-Hull');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LA', 'Lancaster');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LE', 'Leeds');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LI', 'Leicester');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LF', 'Lichfield');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LC', 'Lincoln');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LV', 'Liverpool');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LN', 'London');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('MA', 'Manchester');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('MK', 'Milton Keynes');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('NT', 'Newcastle-upon-Tyne');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('NR', 'Norwich');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('NG', 'Nottingham');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('OX', 'Oxford');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('PB', 'Peterborough');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('PL', 'Plymouth');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('PM', 'Portsmouth');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('PR', 'Preston');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('RP', 'Ripon');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SA', 'Salford');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SS', 'Salisbury');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SF', 'Sheffield');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SO', 'Southampton');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SD', 'Southend-on-Sea');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SA', 'St Albans');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('ST', 'Stoke on Trent');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SU', 'Sunderland');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('TR', 'Truro');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('WK', 'Wakefield');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('WE', 'Wells');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('WM', 'Westminster');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('WC', 'Winchester');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('WO', 'Wolverhampton');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('WR', 'Worcester');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('YK', 'York');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('AR', 'Armagh');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('BG', 'Bangor');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('BF', 'Belfast');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LS', 'Lisburn');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('LD', 'Londonderry');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('NR', 'Newry');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('AB', 'Aberdeen');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('DU', 'Dundee');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('DF', 'Dunfermline');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('ED', 'Edinburgh');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('GL', 'Glasgow');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('IV', 'Inverness');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('PH', 'Perth');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('ST', 'Stirling');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('CA', 'Cardiff');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('NP', 'Newport');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('AS', 'St Asaph');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SD', 'St Davids');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('SW', 'Swansea');
INSERT INTO CITIES (CI, CITY_NAME) VALUES ('WX', 'Wrexham');
